# Generated by Django 5.0.1 on 2026-02-14 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('current_stage', models.CharField(default='intro', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('stack', models.JSONField(default=list)),
                ('rubric_template', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('snippet', models.TextField()),
                ('confidence_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='interviews.interviewsession')),
            ],
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.jobposting'),
        ),
    ]
