# Generated by Django 6.0.2 on 2026-02-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_evidencesnippet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerAnswerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.TextField()),
                ('candidate_answer', models.TextField()),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('evidence_extracted', models.TextField(blank=True, null=True)),
                ('is_cheating_suspected', models.BooleanField(default=False)),
                ('cheating_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('bias_flag', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interviewsession')),
            ],
        ),
    ]
