# Generated by Django 6.0.2 on 2026-02-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_peranswermetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='peranswermetric',
            name='critique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peranswermetric',
            name='ideal_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peranswermetric',
            name='technical_concepts_missed',
            field=models.JSONField(default=list),
        ),
    ]
